# Codecov Configuration for Monorepo
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto

# Fix path mapping for monorepo structure
fixes:
  - "out/::" # Remove out/ prefix from paths
  - "extensions/git-id-switcher/out/::extensions/git-id-switcher/src/" # Map compiled to source

# Ignore test files from coverage
ignore:
  - "**/*.test.ts"
  - "**/test/**"
  - "**/out/test/**"
