# Codecov Configuration for Monorepo
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto

# Fix path mapping for monorepo structure
# With sourceMap enabled, lcov.info contains paths like "src/commandAllowlist.ts"
# These need to be mapped to full repository paths
fixes:
  - "src/::extensions/git-id-switcher/src/"

# Ignore test files from coverage
ignore:
  - "**/*.test.ts"
  - "**/test/**"
