# Codecov Configuration for Monorepo
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        # Require status check to pass (not informational)
        informational: false
    patch:
      default:
        # New code must have 100% coverage
        target: 100%
        threshold: 0%
        informational: false

# Fix path mapping for monorepo structure
# With sourceMap enabled, lcov.info contains paths like "src/commandAllowlist.ts"
# These need to be mapped to full repository paths
fixes:
  - "src/::extensions/git-id-switcher/src/"

# Ignore test files from coverage
ignore:
  - "**/*.test.ts"
  - "**/test/**"
