name: DCO

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dco:
    name: DCO Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Run DCO Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'dco-check==0.5.0 --hash=sha256:3c027d2d47b5cbb03f7e2a25ec8ffb56d8a33c49563c8fcd2cef443ebf3cff0d' > /tmp/requirements-dco.txt
          pip install --require-hashes --no-deps -r /tmp/requirements-dco.txt
          dco-check --exclude-pattern '(dependabot|renovate)\[bot\]'
